### ISSUE TITLE
Verify where ssl is terminated

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/asb-hack#125]
Where is SSL terminated in the current traffic route from internet to k8s pods?
How can we verify?

Could be a challenge

Answer:
These docs cover the setup we're using. https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-end-to-end-ssl-powershell

>Application Gateway terminates the TLS/SSL connection at the application gateway. The gateway then applies the routing rules to the traffic, re-encrypts the packet, and forwards the packet to the appropriate back-end server based on the routing rules defined. Any response from the web server goes through the same process back to the end user.

**Comment by bartr** [comment]
- Can we add this to the overview presentation?

**Comment by bartr** [comment]
@AAkindele - I believe this is in the presentation - can we close?

**Comment by AAkindele** [comment]
yep. this can be closed. I've updated the issue with docs that cover our ASB setup.
