### ISSUE TITLE
Update setup.sh to use codespace secrets for certs

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/asb-hack#260]
setup.sh is currently using a shared key vault for App gateway, and cluster ingress certificates. Update the script to use the codespace secrets and remove requirement on the shared key vault. This will allow a deployment to use the instance key vault that is created by the ARM template.

The values in the AKS cluster ARM templates that need updates are appGatewayListenerCertificate, aksIngressControllerCertificate, and aksIngressControllerKey

**Comment by bartr** [comment]
@AAkindele - I believe this is done - can we close?

**Comment by AAkindele** [comment]
That has not been done yet. Only `airs-setup.sh` is using the codespace secrets.
