### ISSUE TITLE
AIRS - create DNS entry without granting permissions

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#265]
Hack participants need to create a DNS `A` record as part of the deployment. The DNS zone that needs to be updated is in a different subscription that participants will not have access to. Setup a GitHub action that can create the required `A` record for the participant in the DNS zone for the hack.

Plan: https://github.com/retaildevcrews/asb-hack/issues/265#issuecomment-856483059

**Comment by bartr** [comment]
- this could be as simple as outputting the command and copy / paste into Teams where a coach could create it
- they still have to deploy everything, so a little delay won't hurt

**Comment by bartr** [comment]
- we should be able to do this with a github action
  - create a SP with permissions and store as GitHub secrets
  - login to Azure with those creds
  - create a file when they check in their branch for flux setup
  - have a github action run on every branch except master when that file changes
  - use az cli to create the DNS entry
  - we might be able to delete the DNS entry when the branch is deleted

**Comment by bartr** [comment]
Check Azure quota on DNS records in a single public DNS Zone

Hack participants will be creating DNS `A` records in the aks-sb.com dns zone. Is there a risk of hitting a limit of allowed dns records?

**Comment by AAkindele** [comment]
DNS record limit is 10,000 per public DNS zone. So we're good there. https://docs.microsoft.com/en-us/azure/dns/dns-zones-records#limits

GitHub Actions limit are 180 concurrent jobs. Jobs after that are queued. So we're good here as well. https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits
