### ISSUE TITLE
Develop Challenge 4 - deploy loderunner

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#280]
- Create a challenge to deploy loderunner in challenges folder. See existing challenges for reference. https://github.com/retaildevcrews/asb-spark/tree/main/challenges
- Record a coach's video walking coaches through through the solution of the challenge. See this video for reference [ghcr challenge coach video](https://msit.microsoftstream.com/video/3ea90840-98dc-869d-832f-f1ebc818510c?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468)

notes: https://github.com/retaildevcrews/asb-hack/issues/280#issuecomment-856487636

**Comment by bartr** [comment]
- we should walk them through using WebV to run a baseline and benchmark test interactively
- give them the data to create the yaml but not the actual yaml
- something like:
- namespace: ngsa
- container: ghcr.io/retaildevcrews/ngsa-lr:beta
- args -s ... -f ... -r --prometheus
- ClusterIP: 8080
- etc.

**Comment by AAkindele** [comment]
- use loderunner docker container to run it interactively and deploy it to cluster. **not using webv**
- hit the dns address for the deployed instance.
