### ISSUE TITLE
Record ASB Overview Session

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#282]

**Comment by AAkindele** [comment]
Recording session with PnP team is scheduled for June 30th. The back up plan for the coaches training is to use the videos from One CSE Week.
- [part 1](https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-5f7b-f1ebb810bf2b?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468)
- [part 2](https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-1e9d-f1ebb810d1a2?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468)
