### ISSUE TITLE
Add ASB upskilling video to RDC demos channel.

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#299]
-  Several folks did not have as much experience with ASB, not sure if I saw a video walkthrough on ASB on the RDC demos channel but this would have been great for quick upskilling

**Comment by bartr** [comment]
This is part of "train-the-trainer". Should add a link to the HackGuide

**Comment by AAkindele** [comment]
videos are in our channel. I'll add links to the hack guide.
- [part 1](https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-5f7b-f1ebb810bf2b?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468)
- [part 2](https://msit.microsoftstream.com/video/e59c0840-98dc-a7ab-1e9d-f1ebb810d1a2?channelId=533aa1ff-0400-85a8-6076-f1eb81fb8468)
