### ISSUE TITLE
Add screen shots of Azure portal that illustrate ASB overview

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#300]

**Comment by bartr** [comment]
The goal of this repo is to allow hackers to get ASB up and running quickly.

An anti-pattern is to teach them about ASB. That content should be in the PnP repo so that we don't have duplicate / competing content.

Check the PnP repo to see if this exists. If not, we can PR to the upstream repo.

**Comment by bartr** [comment]
- @AAkindele - can this be covered in the intro video?

**Comment by AAkindele** [comment]
Yep. I can add the screenshots to the presentation slides.

**Comment by AAkindele** [comment]
screenshots have been added to presentation slides
