### ISSUE TITLE
Include network flow in repo

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#310]
https://github.com/retaildevcrews/ngsa/tree/jkeane/archdocs/docs/arch#pnp-request-routing---monitoring-dev-cluster

**Comment by bartr** [comment]
The goal of this repo is to allow hackers to get ASB up and running quickly.

An anti-pattern is to teach them about ASB. That content should be in the PnP repo so that we don't have duplicate / competing content.

Check the PnP repo to see if this exists. If not, we can PR to the upstream repo.

**Comment by AAkindele** [comment]
Will be adding the screenshots to the presentation slides instead of this repo.

**Comment by AAkindele** [comment]
network flow has been added to the presentation slides.
