### ISSUE TITLE
create sign up sheet

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#318]
- create a sign up sheet (Office Forms)
- capture
  - First Name (preferred)
  - Last Name
  - alias (NOT first.last)
  - GitHub ID
  - Region (Americas, EMEA, APJ)
  - Docker Knowledge (100, 200, 300, 400)
  - Kubernetes Knowledge (100, 200, 300, 400)
  - AKS Secure Baseline (100, 200, 300, 400)

We can use this to automate creating GitHub IDs and adding to security group

**Comment by dsturgell** [comment]
@bartr   Few questions/comments :)

1.  What should be the official title of the form -- ASB Hack?  MS Ready ASB Hack?
2.  We should put more guidance around what 100/200/300/400 means as everyone has different interpretations :)

First pass of meaning:
  - 100: Understand conceptional, No Hands-on experience
  - 200: Limited hands-on experience as a user
  - 300: Good understanding on how it works
  - 400: Deep understanding & understand behind the scenes

**Comment by bartr** [comment]
@dsturgell 

From the Spark site

- 100 Foundational
- 200 Intermediate
- 300 Advanced
- 400 Expert

**Comment by bartr** [comment]
@dsturgell 

We will want to use this with the coaches as well. Request for coaches is going out 6/11

**Comment by dsturgell** [comment]
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5qEJ2JLzGxFrwahRqWTUkdUMVdaUDhHVUpDVktVSzcySDhaOTRQME02Vi4u
