### ISSUE TITLE
Cleanup script does not purge key vault

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/asb-hack#322]
cleanup.sh and airs-cleanup.sh are not purging the key vault before deleting the core resource group. After running the cleanup script, the key vaults are still in the soft deleted state. The cleanup script should delete and purge.

scripts:
https://github.com/retaildevcrews/asb-hack/blob/main/cleanup.sh
https://github.com/retaildevcrews/asb-hack/blob/main/airs-cleanup.sh

**Comment by bartr** [comment]
Is the below code not working?  It was working during OCW - not sure if something changed?

```bash

if [ -v "$ASB_KEYVAULT_NAME" ]
then
  # delete and purge the key vault
  az keyvault delete -n $ASB_KEYVAULT_NAME
  az keyvault purge -n $ASB_KEYVAULT_NAME
fi

```

**Comment by bartr** [comment]
- tested several times and it's working now

Closing issue
