### ISSUE TITLE
Plan for porting changes from asb-spark to asb-hack repo

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/asb-hack#344]
Several changes were made in the [asb-spark](https://github.com/retaildevcrews/asb-spark) repo for the SPARK open hack.
The long term [asb-hack](https://github.com/retaildevcrews/asb-hack) repo will need some of these changes ported over.

Changes to asb-spark content that need a decision on whether or not to port to asb-hack. Using [asb-spark PRs](https://github.com/retaildevcrews/asb-spark/pulls?q=is%3Apr+is%3Aclosed) as a guide.

- [ ] remove http-https redirect and turn it into a challenge
  - no. keeping http-https redirect solution in the code.
- [ ] remove ghcr.io from allowed registries and turn it into a challenge
  - no. keep ghcr.io solution in the code.
- [ ] remove setup.sh and cleanup.sh
  - no. keeping both of these scripts
- [ ] update dev container to use webv 2.0 release
  - yes. https://github.com/retaildevcrews/asb-spark/pull/17/files
- [ ] Hack challenges folder
  - challenges from asb-spark have been copied over to asb-hack
- [ ] remove airs-setup.sh and airs-cleanup.sh
  - ?
- [ ] add commands from setup and cleanup scripts to README.
  - ?
- [ ] updates to hack guide docs
  - ?
  - https://github.com/retaildevcrews/asb-spark/pull/16/files
  - https://github.com/retaildevcrews/asb-spark/pull/2/files
- [ ] update k8s node pool VM size from D series and ephemeral disks, to A series and managed disks
  - ?
- [ ] updates to README
  - ?
  - https://github.com/retaildevcrews/asb-spark/pull/11/files
  - https://github.com/retaildevcrews/asb-spark/pull/2/files
- [ ] break up namespaces.yaml file and move to related directories
  - ?
- [ ] add code owners file
  - ?
- [ ] add github action to create dns records for hack participants
  - ?

**Comment by bartr** [comment]
we had at least one PR go into asb-hack that isn't in asb-spark so need to make sure not to lose any work

**Comment by bartr** [comment]
- many of the changes will need to go into the AIRS docs
- We need a strategy on maintaining an AIRS and non-AIRS version (or do we just do AIRS?)

**Comment by bartr** [comment]
PR merged
