### ISSUE TITLE
http doesn't work in jumpbox

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#347]
- http quit working in the jumpbox
- discovered on k8s-quickstart repo

**Comment by joheec** [comment]
https://gitmemory.com/issue/httpie/httpie/1092/863807846

**Comment by bartr** [comment]
I pushed the changes to your branch - it should work now

We need to go back to other images and use the `pip3 install` method as it installs a much later version of http than `apt-get`
