### ISSUE TITLE
Onboard to OpenHack

### ISSUE THREAD

**Issue by ckittel** [retaildevcrews/asb-hack#354]
Microsoft OpenHacks are an [internal](https://microsoft.sharepoint.com/teams/WWLFieldTrainerStaffing/Lists/Field%20Trainer%20Event%20List/AllIEvents.aspx) and [customer-facing](https://openhack.microsoft.com) brand and experience that is very well suited for this content. There is a defined runway and onboarding process to join the few existing OpenHacks as cannon material. Until this content is there, we'll want to ensure that we're not positioning this content as an offiical OpenHack (which might imply Acclaim badging and TSI credit).

The path to onboard to OpenHacks are managed by a team in CSE lead by Tristan Gorringe, and more info can be found at <https://aka.ms/OpenHackProgram>.  IIRC, WW Learning handles the Internal Facing logistics while GSMO focuses on customer & partner-facing hacks.

**Comment by bartr** [comment]
cc: @RobBagby 

- There is no TSI credit for this hack in FY22. The cutoff was already past when we started the conversation.
- I believe this is considered an "OpenHack light" - Rob can validate

**Comment by ckittel** [comment]
Correct. This is an issue to consider elevating this content for _future_
"non-lite" status and until then making sure we don't confuse anyone to
think that it already is.

**Comment by bartr** [comment]
This question came up several times during the hacks, so there's definitely interest.

closing as we addressed during the hacks
