### ISSUE TITLE
Azure Bastion in "southeastasia" region

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/asb-hack#357]
A hack participant reported that Azure bastion is not available in the southeastasia region.
[This page](https://azure.microsoft.com/en-us/services/azure-bastion) says it is not available.
But [this update page](https://azure.microsoft.com/en-us/updates/azure-bastion-is-now-available-in-20-new-regions/) published in 2020 says it is.

Verify the availability in the southeastasia region. If it is not available in that region, remove from README.

**Comment by bartr** [comment]
updated readme

closing
