### ISSUE TITLE
policy prevents pulling from ghcr.io

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/asb-hack#65]
- temporarily added ngsa-app and ngsa-lr to docker hub

**Comment by bartr** [comment]
@joaquinrz - now that OCW is in the books, can you merge this PR please? It will make deploying other workloads a lot easier.

**Comment by joaquinrz** [comment]
@bartr @kforeverisback  I am currently working in the PR to add `*.ghcr.io` and `*.githubusercontent.com` to the ARM template, is the regex mentioned above still required as part of this PR?
